<?php

namespace AppBundle\Repository;

/**
 * AsmakhRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsmakhRepository extends \Doctrine\ORM\EntityRepository
{
}
