<?php

namespace AppBundle\Repository;

/**
 * AsmaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsmaRepository extends \Doctrine\ORM\EntityRepository
{
}
