<?php

namespace AppBundle\Repository;

/**
 * finalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class finalRepository extends \Doctrine\ORM\EntityRepository
{
}
