<?php

namespace AppBundle\Repository;

/**
 * InsectesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsectesRepository extends \Doctrine\ORM\EntityRepository
{
}
